WIP - Documentation initiale
139bercy/decp-docs pull request #4
Opened 2020-05-05 16:02 UTC by ColinMaudry

Cette documentation décrit sommairement la situation actuelle, avant les changements à venir :

- transfert des dépôts de code
- publication parallèle des données sur data.gouv.fr et data.economie.gouv.fr
- publication de données brutes et de données raffinées

closes #3 #2

2020-05-05 16:23 UTC, strainel requested changes
merci @ColinMaudry 
dans l'ensemble, je n'ai pas trop de remarques à ce stade ; j'ai juste fait quelques propositions.

2020-05-05 16:23 UTC, strainel commented on content/contexte/_index.md
> +Conscient de leur valeur, la mission Etalab puis le Ministère de l'Économie et des Finance ont entrepris de rassembler ces données dans un même jeu de données afin d'accroître leur visibilité et stim
```suggestion
Conscient de leur valeur, la mission Etalab et le ministère de l'Économie et des Finances ont entrepris de rassembler ces données dans un même jeu de données afin d'accroître leur visibilité et stimuler leur réutilisation par la société civile et les acheteurs eux-mêmes.
```

2020-05-05 16:23 UTC, strainel commented on content/contexte/_index.md
> +Les profils d'acheteurs qui publient leurs données sur data.gouv.fr :
peut-être commencer par ajouter un texte du genre : les profils acheteurs absents peuvent être intégrés en prenant attache via la boite aux lettres...

2020-05-05 16:23 UTC, strainel commented on content/donnees.md
> +Afin de faciliter leur réutilisation, l'État a rassemblé les données publiées par les partenaires et les profils d'acheteur dans un jeu de données unique.
```suggestion
Afin de faciliter leur réutilisation, l'État rassemble les données publiées par les partenaires et les profils d'acheteurs dans un jeu de données unique.
```

2020-05-05 16:23 UTC, strainel commented on content/donnees.md
> +De plus, nous profitons de cette étape de consolidation pour effectuer quelques opérations de montée en qualité et de résolution des anomalies.
```suggestion
Au cours de cette étape de consolidation, des opérations de mise en qualité et de résolution des anomalies sont réalisées.
```

2020-05-05 16:23 UTC, strainel commented on content/donnees.md
> +![Progression du nombre de marchés par source](https://plot.ly/~ColinMaudry/1.png)
```suggestion
Un outil de supervision des données est disponible ![ici](https://139bercy.github.io/decp-monitoring/)
```

2020-05-06 11:26 UTC, strainel commented on content/donnees.md
> +![Progression du nombre de marchés par source](https://plot.ly/~ColinMaudry/1.png)
Je viens de remettre à jour à la main le tableau de bord... des petits soucis de répertoire avec les caches CircleCI... me suis inspiré de celui que tu avais fait, j'ai ajouté le slider.

2020-05-06 11:42 UTC, ColinMaudry commented on content/donnees.md
> +![Progression du nombre de marchés par source](https://plot.ly/~ColinMaudry/1.png)
Done

2020-05-06 11:42 UTC, ColinMaudry commented on content/donnees.md
> +De plus, nous profitons de cette étape de consolidation pour effectuer quelques opérations de montée en qualité et de résolution des anomalies.
Je trouve la tournure passive très impersonnelle, mais soit :)

2020-05-06 11:53 UTC, strainel commented on content/donnees.md
> +De plus, nous profitons de cette étape de consolidation pour effectuer quelques opérations de montée en qualité et de résolution des anomalies.
Oui je sais bien... mais le "nous" n'est jamais très clair. J'aime bien le côté neutre.

2020-05-12 10:36 UTC, ColinMaudry commented on content/contexte/_index.md
> +Les profils d'acheteurs qui publient leurs données sur data.gouv.fr :
Quelle boîte aux lettres ? :)

Je vais mettre un TODO en attendant qu'on clarifie le process de support.

2020-05-12 10:40 UTC, ColinMaudry commented on content/donnees.md
> +De plus, nous profitons de cette étape de consolidation pour effectuer quelques opérations de montée en qualité et de résolution des anomalies.
Done

2020-05-12 10:40 UTC, ColinMaudry commented on content/contexte/_index.md
> +Les profils d'acheteurs qui publient leurs données sur data.gouv.fr :
Done

2020-05-12 10:44 UTC, ColinMaudry commented
Au point où ça en est, je pense qu'on peut merger.

Les points suivants doivent avancer pour pouvoir finaliser la documentation :

- mise en place d'un thème et d'une structure de fichiers (pour finaliser les liens)
- mise du process de support de l'écosystème (pour les modalités de contact)
- migration du code d'Etalab vers 139bercy pour finaliser les liens vers le code
- mise en place des différentes publication de données (brutes, raffinées, data.gouv.fr, data.economie.gouv.fr, etc.) pour finaliser la partie sur l'aperçu des données publiées

2020-05-12 11:30 UTC, strainel approved these changes

2020-05-13 07:55 UTC, merged